# Generated by Django 4.1.5 on 2023-02-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upname', models.CharField(max_length=30)),
                ('upprice', models.IntegerField()),
                ('updiscription', models.CharField(max_length=30)),
                ('upfile', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cardpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.IntegerField()),
                ('cardexpiration', models.CharField(max_length=30)),
                ('securitycode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upname', models.CharField(max_length=30)),
                ('upprice', models.IntegerField()),
                ('updiscription', models.CharField(max_length=30)),
                ('upfile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='shopregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('uaddress', models.CharField(max_length=30)),
                ('ushopid', models.IntegerField()),
                ('uemail', models.EmailField(max_length=254)),
                ('uphone', models.IntegerField()),
                ('upassword', models.CharField(max_length=20)),
                ('upassword2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='uploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upname', models.CharField(max_length=30)),
                ('upprice', models.IntegerField()),
                ('updiscription', models.CharField(max_length=30)),
                ('upfile', models.ImageField(upload_to='rc/static')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upname', models.CharField(max_length=30)),
                ('upprice', models.IntegerField()),
                ('updiscription', models.CharField(max_length=30)),
                ('upfile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
