# Generated by Django 4.1.5 on 2023-02-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0003_cart_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
